### ISSUE TITLE
How to use CONRAD released version.

### ISSUE THREAD

**Issue by leiwang1023** [akmaier/CONRAD#124]
Dear CONRAD's developer:

I am a student of Xi'Dian University in China. Firstly, thanks for reading this email.

Recently, I am interested in Cardiac CT Perfusion (CCTP). So I want to simulate cardiac and it's motion. CONRAD is a multifunctional software for medical physics. But I am newer for CT reconstruction and java. when I  use CONRAD 1.0.8 released version to reconstruction the Cardiac Model， there is nothing to do after the following operations:

   Click Conrad.bat ->  CONRAD -> Create Numerical Phantom -> projection phantom.

I was wondering if you could offer me a simple example of tutorial of cardiac CT reconstruction for future study.

Thank you very much for your kind contribution and I am looking forward to your early reply.

Sincerely, yours

Lei Wang

**Comment by tmgeimer** [comment]
Dear Lei Wang,

we are aware of this and it is in fact a *.jar-related bug.
Short explanation: After calling the phantom creation process, there should appear a list of phantoms to choose from (e.g. the Conard Cardiac Model). This is achieved by parsing the directory for the appropriate class-files. However, within the packaged jar-file, this parsing does not work correctly. Conseqeuently, indexing an an empty list results in the IndexOutOfBoundsException you probably noticed in the command window. We are working on this, but there's no expected time of availability yet.

Since this problem only occurs in the execution of the *.jar-file, the simplest solution would be to download CONRAD from GitHub and build it yourself using the JDK & Eclipse.
Afterwards, simply run the ReconstructionPipelineFrame.java and proceed as normal.

For tutorials on how to do projections and reconstruction, please check out [https://www5.cs.fau.de/conrad/home/](https://www5.cs.fau.de/conrad/home/).
Files for the Cardiac Model can be found here: [https://www5.cs.fau.de/conrad/data/heart-model/](https://www5.cs.fau.de/conrad/data/heart-model/).

I hope this answer was helpful to you. If you have any further questions feel free to contact us.

Best,
Tobias
